version: "3"

services:
  postgres:
    image: "postgres:10-alpine"
    container_name: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - '${DB_DATA_PATH:-./.pgdata}:/var/lib/postgresql/data'

  api:
    image: "node:12-alpine"
    container_name: "file-meta-api"
    volumes:
      - "./:/source"
    working_dir: /source
    depends_on:
      - postgres
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
    command: sh -c "yarn && yarn start:dev"
